name: Deploy Worker

on:
  push:
  pull_request:
  repository_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3

      # Add this step to set up Node.js version 20
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Explicitly set Node.js version to 20

      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
